#!/bin/sh

set -e

composer install

export PATH="$HOME/.composer/vendor/bin:$PATH"

if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
  composer global require "phpunit/phpunit=5.6.*"
else
  composer global require "phpunit/phpunit=4.8.*"
fi

composer global require wp-coding-standards/wpcs
phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
