#!/bin/sh

set -e

wp-pot \
  --domain jekyll-export \
  --dest-file languages/jekyll-export.pot \
  --src "jekyll-exporter.php" \
  --package "WordPress Jekyll Export 2.2.0" --relative-to "." \
  --comment-keyword "translators:"
