#!/bin/sh

set -e

echo "Verifying mysql is up..."
pgrep mysql > /dev/null || sudo service mysql start 

export PATH="$HOME/.composer/vendor/bin:./bin:$PATH"

echo "Running unit tests..."
script/cibuild-phpunit

echo "Running Style checks..."
script/cibuild-phpcs
