#!/bin/sh

set -e

export PATH="$HOME/.composer/vendor/bin:./bin:$PATH"

phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
phpcs --standard=phpcs.ruleset.xml -p -s --colors *.php */**.php
