#!/bin/sh

set -e

export PATH="$TRAVIS_BUILD_DIR/vendor/squizlabs/php_codesniffer/bin:$PATH"

phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/vendor/wp-coding-standards/wpcs
phpcs --standard=phpcs.ruleset.xml -p -s --colors *.php */**.php -v