#!/bin/sh

set -e

export PATH="$HOME/.composer/vendor/bin:./bin:$PATH"

echo "Running Style checks..."
phpcs --standard=phpcs.ruleset.xml -p --warning-severity=0 $(find . -name '*.php' -not -path "./vendor/*")

echo "Running unit tests..."
phpunit
