#!/bin/bash

set -e

VERSION=$(grep -i "Stable tag:" docs/header.md | awk -F' ' '{print $NF}' | tr -d '\r')

wp-pot \
  --domain jekyll-export \
  --dest-file languages/jekyll-export.pot \
  --src "jekyll-exporter.php" \
  --package "WP Document Revisions $VERSION" --relative-to "." \
  --comment-keyword "translators:"
