name: AI Community Moderator

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  moderate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      discussions: write
      models: read
    steps:
      - uses: benbalter/ai-community-moderator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
